//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a New-StronglyTypedCsFileForResx funciton.
//     To add or remove a member, edit your .ResX file then rerun buildCoreClr.ps1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PackageManagement.Msi.Internal.Resources {
using System;
using System.Reflection;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]

internal class Messages {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Messages() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PackageManagement.Msi.Internal.Resources.Messages", typeof(Messages).GetTypeInfo().Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Installing ...
    /// </summary>
    internal static string Installing {
        get {
            return ResourceManager.GetString("Installing", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Installing a MSI package from '{0}'
    /// </summary>
    internal static string InstallingMSIPackage {
        get {
            return ResourceManager.GetString("InstallingMSIPackage", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Reboot is required to complete the installation operation.
    /// </summary>
    internal static string InstallRequireReboot {
        get {
            return ResourceManager.GetString("InstallRequireReboot", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Uninstalling ...
    /// </summary>
    internal static string UnInstalling {
        get {
            return ResourceManager.GetString("UnInstalling", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Uninstalling a MSI package '{0}'
    /// </summary>
    internal static string UninstallingMSIPackage {
        get {
            return ResourceManager.GetString("UninstallingMSIPackage", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Reboot is required to complete the uninstallation operation.
    /// </summary>
    internal static string UninstallRequireReboot {
        get {
            return ResourceManager.GetString("UninstallRequireReboot", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Uninstallation operation failed. Please look at '{0}' file for details.
    /// </summary>
    internal static string PackageFailedToUnInstallErrorLog {
        get {
            return ResourceManager.GetString("PackageFailedToUnInstallErrorLog", resourceCulture);
        }
    }

}
}
