//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find base Powershell module folder..
        /// </summary>
        public static string CantFindBasePowerShellModuleFolder {
            get {
                return ResourceManager.GetString("CantFindBasePowerShellModuleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to import the provider &apos;{0}&apos; because the provider with the same name also exists from path &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateProviderName {
            get {
                return ResourceManager.GetString("DuplicateProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import-PackageProvider &apos;{0}&apos; failed..
        /// </summary>
        public static string FailedToImportProvider {
            get {
                return ResourceManager.GetString("FailedToImportProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import-Module failed: &apos;{0}&apos;..
        /// </summary>
        public static string ImportModuleFailed {
            get {
                return ResourceManager.GetString("ImportModuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module &apos;{0}&apos; is already loaded..
        /// </summary>
        public static string ModuleAlreadyLoaded {
            get {
                return ResourceManager.GetString("ModuleAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find provider &apos;{0}&apos; under the specified path..
        /// </summary>
        public static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PackageManagementProviders&apos; key is not found in the .psd1 file under &apos;{0}&apos;..
        /// </summary>
        public static string PackageManagementProvidersNotFound {
            get {
                return ResourceManager.GetString("PackageManagementProvidersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script &apos;{0}&apos; Function &apos;{1}&apos; returns null..
        /// </summary>
        public static string PowershellScriptFunctionReturnsNull {
            get {
                return ResourceManager.GetString("PowershellScriptFunctionReturnsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find provider &apos;{0}&apos;. Please check if the ProviderName is set to &apos;{1}&apos; in &apos;{2}&apos;. .
        /// </summary>
        public static string ProvideNameMismatch {
            get {
                return ResourceManager.GetString("ProvideNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the provider &apos;{0}&apos; is null, empty or not implemented by the provider..
        /// </summary>
        public static string ProviderNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ProviderNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root module {0} does not match the packagemanagementprovider name {1}..
        /// </summary>
        public static string RootModuleAndPackageManagementProviderNameNotMatch {
            get {
                return ResourceManager.GetString("RootModuleAndPackageManagementProviderNameNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script failure at : {0}.
        /// </summary>
        public static string ScriptStackTrace {
            get {
                return ResourceManager.GetString("ScriptStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded PowerShell package provider: &apos;[{0}]&apos;..
        /// </summary>
        public static string SuccessfullyLoadedModule {
            get {
                return ResourceManager.GetString("SuccessfullyLoadedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find package provider &apos;{0}&apos; under the specified path..
        /// </summary>
        public static string UnableToFindModuleProvider {
            get {
                return ResourceManager.GetString("UnableToFindModuleProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;PackageProviderFunctions.psm1&apos; at &apos;{0}&apos;.
        /// </summary>
        public static string UnableToFindPowerShellFunctionsFile {
            get {
                return ResourceManager.GetString("UnableToFindPowerShellFunctionsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load module &apos;{0}&apos; because no valid provider found under the specified path..
        /// </summary>
        public static string UnableToLoadModule {
            get {
                return ResourceManager.GetString("UnableToLoadModule", resourceCulture);
            }
        }
    }
}
