name: $(BuildDefinitionName)-$(date:yyMM).$(date:dd)$(rev:rrr)
trigger: none
pr: none

variables:
  - group: ESRP
  - name: ModuleName 
    value: 'PackageManagement'
  - name: BuildOutputPath
    value: '$(BuildSourcePath)\out\PackageManagement'
  - name: SignedOutputPath
    value: '$(Build.SourcesDirectory)/signed'
  - name: SourcePath
    value: 'src'
  - name: BuildSourcePath
    value: '$(Build.SourcesDirectory)/$(SourcePath)'

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: Build
  displayName: Build PackageManagement Module Package
  jobs:
  - job: BuildPkg
    displayName: Build Package
    pool:
      name: 1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure

    steps:
    - checkout: self
      clean: true
      submodules: true
    
    - task: NuGetAuthenticate@0
      inputs:
        nuGetServiceConnections: 'InternalPkgMgmtFeed'

    - pwsh: |
        Get-ChildItem -Path env:
      displayName: Capture environment for build
      condition: succeededOrFailed()

    - pwsh: |
        Set-Location $(BuildSourcePath)
        .\bootstrap.ps1
        .\build.ps1 net452
        .\build.ps1 netstandard2.0
        Get-ChildItem ./ -Recurse | Write-Host
      displayName: Build and publish artifact

    - pwsh: |
        $signSrcPath = "$(BuildOutputPath)"
        $vstsCommandString = "vso[task.setvariable variable=signSrcPath]${signSrcPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"

        $outSignPath = "$(BuildOutputPath)"
        $vstsCommandString = "vso[task.setvariable variable=signOutPath]${outSignPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
      displayName: Create fake source and output variables for signing template and no signing
      condition: and(succeeded(), eq(variables['SkipSigning'], 'True'))

    - pwsh: |
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        
        # Created files signing directory
        $srcPath = "$(BuildOutputPath)"
        $createdSignSrcPath = "$(SignedOutputPath)\CreatedFiles"
        if (! (Test-Path -Path $createdSignSrcPath)) {
          $null = New-Item -Path $createdSignSrcPath -ItemType Directory -Verbose
        }
        Copy-Item -Path $srcPath -Dest $createdSignSrcPath -Recurse -Force -Verbose

        $signOutPath = "$(SignedOutputPath)\$(ModuleName)"
        if (! (Test-Path -Path $signOutPath)) {
          $null = New-Item -Path $signOutPath -ItemType Directory
        }

        # Set signing src path variable
        $vstsCommandString = "vso[task.setvariable variable=signSrcPath]${createdSignSrcPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"

        $outSignPath = "$(SignedOutputPath)\$(ModuleName)"
        if (! (Test-Path -Path $outSignPath)) {
          $null = New-Item -Path $outSignPath -ItemType Directory -Verbose
        }
        
        # Set signing out path variable
        $vstsCommandString = "vso[task.setvariable variable=signOutPath]${outSignPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
      displayName: Set up for module created files code signing
      condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True'))

    - pwsh: |
        Write-Host "entering capture environment"
        Write-Host "signSrcPath is"
        Write-Host "$(signSrcPath)"
        Write-Host "signOutPath is"
        Write-Host "$(signOutPath)"
        
        Get-ChildItem -Path . -Recurse -Directory
      displayName: Capture environment for code signing
      condition: succeededOrFailed()

    - pwsh: |
        Write-Host "entering copy already signed files"
        $srcPath = "$(signOutPath)"                         
        Write-Host "signOutPath is"
        Write-Host "$(signOutPath)"
        $signOutPath = "$(Build.SourcesDirectory)/signedOutput/$(ModuleName)"   
        Write-Host "SignedOutputPath\PackageManagement"
        Write-Host "$(SignedOutputPath)\$(ModuleName)

        if (! (Test-Path -Path $signOutPath)) {
          $null = New-Item -Path $signOutPath -ItemType Directory
        }

        Get-ChildItem -Path $srcPath | Foreach-Object {
          if ($_.Attributes -ne "Directory")
          {
            $sig = Get-AuthenticodeSignature -FilePath $_.FullName
            if ($sig.Status -eq 'Valid' -and ($sig.SignerCertificate.Subject -like '*Microsoft*' -and $sig.SignerCertificate.Issuer -like '*Microsoft Code Signing PCA*')) {
              # Copy already signed files directly to output
              Copy-Item -Path $_.FullName -Dest $signOutPath -Force -Verbose 
            }
          }
        }
      displayName: Copy already properly signed files (.dll, .psd1, .psm1, .ps1xml, .mof)
      condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True'))

    - ${{ if ne(variables.SkipSigning, 'True') }}:
      - template: Sbom.yml@ComplianceRepo
        parameters:
          BuildDropPath: $(signOutPath)
          Build_Repository_Uri: 'https://github.com/oneget/oneget'
          PackageName: 'PackageManagement'
          PackageVersion: '1.4.7.1'

    - pwsh: |
        $srcModulePath = Resolve-Path -Path "$(signOutPath)"     #'$(Build.SourcesDirectory)/signedOuput/PackageManagement
        Write-Host "Contents of signOutPath"
        Get-ChildItem $srcModulePath | Write-Host
        $artifactName = "$(ModuleName)"

        $artifactDir = "$(Build.SourcesDirectory)/signedOuput"
        Register-PSRepository -Name "LocalRepo" -SourceLocation "$artifactDir/nupkg"     # "$(Build.SourcesDirectory)/signedOuput/nupkg"
        Publish-Module -Path $srcModulePath -Repository "LocalRepo"
        Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName;]$artifactDir"    #"$(Build.SourcesDirectory)/signedOuput"
      displayName: Create module artifact

# Now on to the compliance stage
- stage: compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - job: ComplianceJob
    pool:
      name: 1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure

    steps:
    - checkout: self
      clean: true
      submodules: true
    - checkout: ComplianceRepo
      clean: true
    - download: current
      artifact: 'PackageManagement'
    - template: script-module-compliance.yml@ComplianceRepo
      parameters:
        # binskim
        AnalyzeTarget: '$(Pipeline.Workspace)/PackageManagement/**/*.dll'
        AnalyzeSymPath: 'SRV*'
        # component-governance - the path to sources
        sourceScanPath: '$(Build.SourcesDirectory)'
        # credscan
        suppressionsFile: ''
        # TermCheck
        optionsRulesDBPath: ''
        optionsFTPath: ''
        # tsa-upload
        # the compliance scanning must be uploaded, which you need to request
        codeBaseName: 'PackageManagement_20220302'
        # selections
        APIScan: false # set to false when not using Windows APIs.

- stage: Release
  displayName: Publish Package to PSGallery
  condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), eq(variables['Publish'], 'True'))
  jobs:
  - template: release.yml
