//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OneGet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.OneGet.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create specified folder &apos;{0}&apos;..
        /// </summary>
        internal static string CreatefolderFailed {
            get {
                return ResourceManager.GetString("CreatefolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Package &apos;{0}&apos; failed to install..
        /// </summary>
        internal static string DependentPackageFailedInstall_dependency {
            get {
                return ResourceManager.GetString("DependentPackageFailedInstall_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Path not set..
        /// </summary>
        internal static string DestinationPathNotSet {
            get {
                return ResourceManager.GetString("DestinationPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bootstrap provider &apos;{0}&apos;..
        /// </summary>
        internal static string FailedProviderBootstrap {
            get {
                return ResourceManager.GetString("FailedProviderBootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File from &apos;{0}&apos; failed signature validation. .
        /// </summary>
        internal static string FileFailedVerification {
            get {
                return ResourceManager.GetString("FileFailedVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename specified is not valid..
        /// </summary>
        internal static string InvalidFilename {
            get {
                return ResourceManager.GetString("InvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is required for this operation.
        /// </summary>
        internal static string MissingRequiredParameter {
            get {
                return ResourceManager.GetString("MissingRequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package source &apos;{0}&apos; already exists with that provider..
        /// </summary>
        internal static string PackageSourceExists {
            get {
                return ResourceManager.GetString("PackageSourceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A protocol handler for scheme &apos;{0}&apos; is not available..
        /// </summary>
        internal static string ProtocolNotSupported {
            get {
                return ResourceManager.GetString("ProtocolNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &apos;{0}&apos; failed to load..
        /// </summary>
        internal static string ProviderPluginLoadFailure {
            get {
                return ResourceManager.GetString("ProviderPluginLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download the list of available providers..
        /// </summary>
        internal static string ProviderSwidtagUnavailable {
            get {
                return ResourceManager.GetString("ProviderSwidtagUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal of the environment variable &apos;{0}&apos; requires elevation.
        /// </summary>
        internal static string RemoveEnvironmentVariableRequiresElevation {
            get {
                return ResourceManager.GetString("RemoveEnvironmentVariableRequiresElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A protocol handler for scheme &apos;{0}&apos; is not available..
        /// </summary>
        internal static string SchemeNotSupported {
            get {
                return ResourceManager.GetString("SchemeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source location &apos;{0}&apos; is not valid for this provider..
        /// </summary>
        internal static string SourceLocationNotValid_Location {
            get {
                return ResourceManager.GetString("SourceLocationNotValid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy file to destination &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToCopyFileTo {
            get {
                return ResourceManager.GetString("UnableToCopyFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create shortcut for file &apos;{0}&apos; that does not exist .
        /// </summary>
        internal static string UnableToCreateShortcutTargetDoesNotExist {
            get {
                return ResourceManager.GetString("UnableToCreateShortcutTargetDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download from URI &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToDownload {
            get {
                return ResourceManager.GetString("UnableToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; failed to install..
        /// </summary>
        internal static string UnableToInstallPackage_package_reason {
            get {
                return ResourceManager.GetString("UnableToInstallPackage_package_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to overwrite existing file &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToOverwriteExistingFile {
            get {
                return ResourceManager.GetString("UnableToOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove existing file &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToRemoveFile {
            get {
                return ResourceManager.GetString("UnableToRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve package dependency -- package &apos;{0}&apos; not found..
        /// </summary>
        internal static string UnableToResolveDependency_dependencyPackage {
            get {
                return ResourceManager.GetString("UnableToResolveDependency_dependencyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve package reference &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToResolvePackage {
            get {
                return ResourceManager.GetString("UnableToResolvePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve package source &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToResolveSource_NameOrLocation {
            get {
                return ResourceManager.GetString("UnableToResolveSource_NameOrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to uninstall package..
        /// </summary>
        internal static string UnableToUninstallPackage {
            get {
                return ResourceManager.GetString("UnableToUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Folder Id &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownFolderId {
            get {
                return ResourceManager.GetString("UnknownFolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find package provider &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownProvider {
            get {
                return ResourceManager.GetString("UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive file type is not supported..
        /// </summary>
        internal static string UnsupportedArchive {
            get {
                return ResourceManager.GetString("UnsupportedArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider type is not supported..
        /// </summary>
        internal static string UnsupportedProviderType {
            get {
                return ResourceManager.GetString("UnsupportedProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? not used ???.
        /// </summary>
        internal static string UriSchemeNotSupported_Scheme {
            get {
                return ResourceManager.GetString("UriSchemeNotSupported_Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User declined to install untrusted package &apos;{0}&apos;..
        /// </summary>
        internal static string UserDeclinedUntrustedPackageInstall {
            get {
                return ResourceManager.GetString("UserDeclinedUntrustedPackageInstall", resourceCulture);
            }
        }
    }
}
