//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerShell.OneGet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerShell.OneGet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:AskPermission.
        /// </summary>
        internal static string AskPermission {
            get {
                return ResourceManager.GetString("AskPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Installing after failing &apos;{0}&apos;.
        /// </summary>
        internal static string ContinueInstallingAfterFailing {
            get {
                return ResourceManager.GetString("ContinueInstallingAfterFailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue uninstalling after failing &apos;{0}&apos;.
        /// </summary>
        internal static string ContinueUninstallingAfterFailing {
            get {
                return ResourceManager.GetString("ContinueUninstallingAfterFailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:DestinationPathInvalid_path.
        /// </summary>
        internal static string DestinationPathInvalid_path {
            get {
                return ResourceManager.GetString("DestinationPathInvalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:DisambiguateForInstall.
        /// </summary>
        internal static string DisambiguateForInstall {
            get {
                return ResourceManager.GetString("DisambiguateForInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:DisambiguateForUninstall.
        /// </summary>
        internal static string DisambiguateForUninstall {
            get {
                return ResourceManager.GetString("DisambiguateForUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:DisambiguateSourceFoundInMultipleProivders.
        /// </summary>
        internal static string DisambiguateSourceFoundInMultipleProivders {
            get {
                return ResourceManager.GetString("DisambiguateSourceFoundInMultipleProivders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded provider &apos;{0}&apos;-- missing option &apos;{1}&apos;.
        /// </summary>
        internal static string ExcludedProviderDueToMissingRequiredOption {
            get {
                return ResourceManager.GetString("ExcludedProviderDueToMissingRequiredOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:GetPackageNotFound.
        /// </summary>
        internal static string GetPackageNotFound {
            get {
                return ResourceManager.GetString("GetPackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Failure {0}.
        /// </summary>
        internal static string InstallationFailure {
            get {
                return ResourceManager.GetString("InstallationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Package &apos;{0}&apos; from untrusted source.
        /// </summary>
        internal static string InstallingPackageFromUntrustedSource {
            get {
                return ResourceManager.GetString("InstallingPackageFromUntrustedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Package.
        /// </summary>
        internal static string InstallPackage {
            get {
                return ResourceManager.GetString("InstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; matches multiple packages &apos;{1}/{2}&apos; ({3}).
        /// </summary>
        internal static string MatchesMultiplePackages {
            get {
                return ResourceManager.GetString("MatchesMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name = &apos;{0}&apos; Location = &apos;{1}&apos; Provider = &apos;{2}&apos;.
        /// </summary>
        internal static string NameLocationProvider {
            get {
                return ResourceManager.GetString("NameLocationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name = &apos;{0}&apos; Location = &apos;{1}&apos; Provider = &apos;{2}&apos; (Replace existing).
        /// </summary>
        internal static string NameLocationProviderReplaceExisting {
            get {
                return ResourceManager.GetString("NameLocationProviderReplaceExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match for package name &apos;{0}&apos;.
        /// </summary>
        internal static string NoMatchForPackageName {
            get {
                return ResourceManager.GetString("NoMatchForPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Package Found {0}.
        /// </summary>
        internal static string NoPackageFound {
            get {
                return ResourceManager.GetString("NoPackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:NoPackagesFoundForProvider_providerName.
        /// </summary>
        internal static string NoPackagesFoundForProvider_providerName {
            get {
                return ResourceManager.GetString("NoPackagesFoundForProvider_providerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Packages Found -- (no package names/criteria listed).
        /// </summary>
        internal static string NoPackagesFoundNoPackageNamesCriteriaListed {
            get {
                return ResourceManager.GetString("NoPackagesFoundNoPackageNamesCriteriaListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:NoProviderSelected.
        /// </summary>
        internal static string NoProviderSelected {
            get {
                return ResourceManager.GetString("NoProviderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:NullOrEmptyPackageSource.
        /// </summary>
        internal static string NullOrEmptyPackageSource {
            get {
                return ResourceManager.GetString("NullOrEmptyPackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Contains Installation Script.
        /// </summary>
        internal static string PackageContainsInstallationScript {
            get {
                return ResourceManager.GetString("PackageContainsInstallationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Contains uninstallation Script.
        /// </summary>
        internal static string PackageContainsUninstallationScript {
            get {
                return ResourceManager.GetString("PackageContainsUninstallationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package File Not Recognized {0}.
        /// </summary>
        internal static string PackageFileNotRecognized {
            get {
                return ResourceManager.GetString("PackageFileNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Install Failure.
        /// </summary>
        internal static string PackageInstallFailure {
            get {
                return ResourceManager.GetString("PackageInstallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package uninstall Failure.
        /// </summary>
        internal static string PackageUninstallFailure {
            get {
                return ResourceManager.GetString("PackageUninstallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ProviderNotFound.
        /// </summary>
        internal static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &apos;{0}&apos; returned no package sources.
        /// </summary>
        internal static string ProviderReturnedNoPackageSources {
            get {
                return ResourceManager.GetString("ProviderReturnedNoPackageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &apos;{0}&apos; returned no package sources (Location = &apos;{1}&apos;).
        /// </summary>
        internal static string ProviderReturnedNoPackageSourcesLocation {
            get {
                return ResourceManager.GetString("ProviderReturnedNoPackageSourcesLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &apos;{0}&apos; returned no package sources (Name = &apos;{1}&apos;).
        /// </summary>
        internal static string ProviderReturnedNoPackageSourcesName {
            get {
                return ResourceManager.GetString("ProviderReturnedNoPackageSourcesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &apos;{0}&apos; returned no package sources (Name = &apos;{1}&apos; Location=&apos;{2}&apos;).
        /// </summary>
        internal static string ProviderReturnedNoPackageSourcesNameLocation {
            get {
                return ResourceManager.GetString("ProviderReturnedNoPackageSourcesNameLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:RequiredValuePackageName.
        /// </summary>
        internal static string RequiredValuePackageName {
            get {
                return ResourceManager.GetString("RequiredValuePackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ShouldContinueAfterPackageInstallFailure.
        /// </summary>
        internal static string ShouldContinueAfterPackageInstallFailure {
            get {
                return ResourceManager.GetString("ShouldContinueAfterPackageInstallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ShouldContinueAfterPackageUnInstallFailure.
        /// </summary>
        internal static string ShouldContinueAfterPackageUnInstallFailure {
            get {
                return ResourceManager.GetString("ShouldContinueAfterPackageUnInstallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ShouldContinueRunningInstallScript.
        /// </summary>
        internal static string ShouldContinueRunningInstallScript {
            get {
                return ResourceManager.GetString("ShouldContinueRunningInstallScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ShouldContinueRunningUninstallScript.
        /// </summary>
        internal static string ShouldContinueRunningUninstallScript {
            get {
                return ResourceManager.GetString("ShouldContinueRunningUninstallScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ShouldContinueWithUntrustedPackageSource.
        /// </summary>
        internal static string ShouldContinueWithUntrustedPackageSource {
            get {
                return ResourceManager.GetString("ShouldContinueWithUntrustedPackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:Should Process Package Install.
        /// </summary>
        internal static string ShouldProcessPackageInstall {
            get {
                return ResourceManager.GetString("ShouldProcessPackageInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:ShouldProcessPackageUnInstall.
        /// </summary>
        internal static string ShouldProcessPackageUnInstall {
            get {
                return ResourceManager.GetString("ShouldProcessPackageUnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the package script at &apos;{0}&apos; be executed?.
        /// </summary>
        internal static string ShouldThePackageScriptAtBeExecuted {
            get {
                return ResourceManager.GetString("ShouldThePackageScriptAtBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the package uninstall script at &apos;{0}&apos; be executed?.
        /// </summary>
        internal static string ShouldThePackageUninstallScriptAtBeExecuted {
            get {
                return ResourceManager.GetString("ShouldThePackageUninstallScriptAtBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:SourceNotFound.
        /// </summary>
        internal static string SourceNotFound {
            get {
                return ResourceManager.GetString("SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package source is not marked as safe. Are you sure you want to install software from &apos;{0}&apos;.
        /// </summary>
        internal static string ThisPackageSourceIsNotMarkedAsSafe {
            get {
                return ResourceManager.GetString("ThisPackageSourceIsNotMarkedAsSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:UnableToResolvePackageProvider.
        /// </summary>
        internal static string UnableToResolvePackageProvider {
            get {
                return ResourceManager.GetString("UnableToResolvePackageProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation Failure {0}.
        /// </summary>
        internal static string UninstallationFailure {
            get {
                return ResourceManager.GetString("UninstallationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Package.
        /// </summary>
        internal static string UninstallPackage {
            get {
                return ResourceManager.GetString("UninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX_THIS_RESOURCE:UnknownProvider.
        /// </summary>
        internal static string UnknownProvider {
            get {
                return ResourceManager.GetString("UnknownProvider", resourceCulture);
            }
        }
    }
}
