//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OneGet.ServicesProvider.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.OneGet.ServicesProvider.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateFolder Failed &apos;{0}&apos; -- {1}.
        /// </summary>
        internal static string CreatefolderFailed {
            get {
                return ResourceManager.GetString("CreatefolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveEnvironmentVariable Failed--Admin Elevation required to remove variable &apos;{0}&apos; from machine context.
        /// </summary>
        internal static string RemoveEnvironmentVariableRequiresElevation {
            get {
                return ResourceManager.GetString("RemoveEnvironmentVariableRequiresElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy file to &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToCopyFileTo {
            get {
                return ResourceManager.GetString("UnableToCopyFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create shortcut - target &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string UnableToCreateShortcutTargetDoesNotExist {
            get {
                return ResourceManager.GetString("UnableToCreateShortcutTargetDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to overwrite existing file &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToOverwriteExistingFile {
            get {
                return ResourceManager.GetString("UnableToOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Folder ID &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownFolderId {
            get {
                return ResourceManager.GetString("UnknownFolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Archive {0}.
        /// </summary>
        internal static string UnsupportedArchive {
            get {
                return ResourceManager.GetString("UnsupportedArchive", resourceCulture);
            }
        }
    }
}
